theme: jekyll-theme-slate

show_downloads: false

github:
  is_project_page: false

title: "tmn505.github.io"
description: "Placeholder for links to binaries published in gh-pages branch of respective repositories"
